### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by philipcmonk** [numerai/submission-criteria#1]
The README should give clear instructions for running the code, and should provide an overview of the code structure.

~~Each file should have a docstring, and most functions as well.  Particular attention should be paid to the originality, concordance, and consistency checks.~~

~~This issue has a 20 NMR bounty.~~

After #11, this issue has an 8 NMR bounty remaing.

**Comment by lorenzofar** [comment]
There should also be a _requirements.txt_ file to install modules necessary to run the code.

**Comment by philipcmonk** [comment]
Is the `setup.py` file not sufficient?  We should have specific installation instructions.

**Comment by lorenzofar** [comment]
Yes, you're right, it is sufficient. (my fault)

**Comment by philipcmonk** [comment]
I do like the idea of specifying general requirements in `setup.py` and locking to a version in `requirements.txt`.

**Comment by philipcmonk** [comment]
Part of this has been completed in #11.  Specifically, we still need instructions for running the code, as well as a high-level description of the code base (both probably in README.md).

The bounty for the remaining portion of the task is 8 NMR.

**Comment by philipcmonk** [comment]
Fixed in number #11 and #16
