### ISSUE TITLE
How is the consistency calculated ?

### ISSUE THREAD

**Issue by anselal** [numerai/submission-criteria#17]
There is no separate thread that calculates the consistency. Am I missing something ???

**Comment by philipcmonk** [comment]
I believe it's scored here: https://github.com/numerai/submission-criteria/blob/820d0f939ae2892f6bdeee02d855ffc0e80958de/database_manager.py#L74-L83

It's fast enough that we do it synchronously.

**Comment by anselal** [comment]
Oh. my bad.
It would be nice though if it was mentioned in the README, since it is not clear in which file it is calculated.

**Comment by philipcmonk** [comment]
Agree.  Do you want to go ahead and add a paragraph or two to the README about where consistency is checked and what it's checking for? Similar to the descriptions of concordance and originality.

**Comment by anselal** [comment]
I will try !!

**Comment by xanderdunn** [comment]
I'll close this, but please feel free to open any pull requests to the documentation.
