### ISSUE TITLE
check originality only vs accepted submissions

### ISSUE THREAD

**Issue by schollinator** [numerai/submission-criteria#20]
this would speed up the process of originality checking, lower the threshold for passing originality, have no negative impact on submission quality...

**Comment by philipcmonk** [comment]
Very much agree.  Arguably, the "check for nearly identical submission" part of the originality check should include all submissions, for performance reasons, but I could see that going either way.

**Comment by zoso95** [comment]
This should be a straight forward change - we just need to change the query we use to get the relevant submissions. Should we change it and launch it for the next tournament?

**Comment by schollinator** [comment]
yes please!

**Comment by philipcmonk** [comment]
Yeah, we should do this for the next tournament if possible.

**Comment by philipcmonk** [comment]
Should this check against submissions with pending originality, or only those with good originality?  If it doesn't check against pending originality, could you cheat by uploading three essentially similar models at the same time?

**Comment by schollinator** [comment]
checking vs  accepted and pending sounds fine, maybe check vs accepted first, then if it passes check vs pending. either way a small downside is that two original contributions being uploaded simultaneously would both be rejected, but that should be pretty rare...

**Comment by philipcmonk** [comment]
I believe in practice it won't make a difference except in unusual circumstances because we only score them one at a time anyway, so any previous submissions *shouldn't* be listed as pending.  However, we may try to parallelize it at some point.

**Comment by xanderdunn** [comment]
This was completed in e1f47642001abcb8015ffe3306c3b4a9b15e6954
