### ISSUE TITLE
Round submissions probabilities

### ISSUE THREAD

**Issue by zoso95** [numerai/submission-criteria#21]
It might make sense to round submission probabilities to 3 decimals to make it more robust to tiny perturbations. Thoughts?

**Comment by kwgoodman** [comment]
Can you share the specific issue you are trying to address?

**Comment by zoso95** [comment]
It was brought up to me in slack that since we are using logloss, a lot of models will tend to centralize around 0.5 and will only be a little ways away from that, and so rounding is likely to be very bad. It was speculated that this would make concordance easier and originality harder, and would make our system more robust, but more bias.
