### ISSUE TITLE
Speed up originality by using hd5 files

### ISSUE THREAD

**Issue by zoso95** [numerai/submission-criteria#27]
hd5 files are a lot faster to read from disk than CSVs. If we change get_submission to write out an hd5 the first time it sees a submission, and then load up an hd5 the next time it is called this will speed up originality when the number of submissions is larger than the cache

**Comment by zoso95** [comment]
Fixed by #34

**Comment by wsteitz** [comment]
Feather (https://github.com/wesm/feather) might be even faster.
