### ISSUE TITLE
Correlation threshold typo in improvements.pdf

### ISSUE THREAD

**Issue by mangstad** [numerai/submission-criteria#6]
![image](https://user-images.githubusercontent.com/1479722/30385435-2462f082-9875-11e7-933f-c4a2484aafa9.png)

The improvements.pdf has a typo in the algorithm for originality. It should be "if The largest correlation coefficient is greater than a threshold (0.95) then The submission is not original." The code correctly checks this threshold.

**Comment by xanderdunn** [comment]
We don't have the source for the PDF, so we can't change this value, but you're right that it's wrong.  I'll close this, but others should be able to find this here.
